### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by ghost** [shopware/swag-docs-rest-api-handling#2]
Wenn ich das Plugin installiere und den Command in der Shell ausführe bekomme ich immer folgenden Fehler:

```
What are the names of all deliveryTime entities
12:25:16 ERROR     [console] Error thrown while running command "swag:api:example". Message: "Client error: `POST http://domain.com/api/oauth/token` resulted in a `405 Method Not Allowed` response:\n{"errors":[{"code":"0","status":"405","title":"Method Not Allowed","detail":"No route found for \u0022GET \/api\/oauth\/ (truncated...)\n" ["exception" => GuzzleHttp\Exception\ClientException^ { …},"command" => "swag:api:example","message" => """  Client error: `POST http://domain.com/api/oauth/token` resulted in a `405 Method Not Allowed` response:\n  {"errors":[{"code":"0","status":"405","title":"Method Not Allowed","detail":"No route found for \u0022GET \/api\/oauth\/ (truncated...)\n  """]

In RequestException.php line 113:

  Client error: `POST http://domain.com/api/oauth/token` resulted in a `405 Method Not Allowed` response:
  {"errors":[{"code":"0","status":"405","title":"Method Not Allowed","detail":"No route found for \u0022GET \/api\/oauth\/ (truncated...)
```

Was mache ich falsch? Am Code habe ich nichts geändert.

**Comment by mitelg** [comment]
hey @Kuhlware 
I could reproduce this and will have a look at this later

**Comment by Kuhlware** [comment]
@mitelg I have in htaccess an ip restriction andI think this is the problem. But how can we fix this? :)

```
<RequireAny>
    Require ipxx.xx.xx.xx
    Require expr %{THE_REQUEST} =~ m#.*?\s+\/api.*?#
</RequireAny>
```

**Comment by mitelg** [comment]
I do not have such config, and have the same problem. so I guess the plugin is simply not in sync with the changes in platform.

**Comment by mitelg** [comment]
hey @Kuhlware 
did you add a username and password in the config of the plugin? once I added them in the admin `/admin#/sw/plugin/settings/RestApiHandling` the command works like intended

**Comment by Kuhlware** [comment]
Yes, I did this, but did not help. The problem should be the htaccess-directoryprotect, because locally in vagrant it works. But I want to test this also on production-shop with htaccess-protect.
